BaseType.create(:nome => "Techmaga")
BaseType.create(:nome => "Orgânica")
BaseType.create(:nome => "Nanorobótica")
BaseType.create(:nome => "Tecnológica pura")
BaseType.create(:nome => "Hibrida techmaga/organica")
