Family.create(:nome => "Datter", :descr => "Branca e Auro não são parentes próximos, ainda que sejam da mesma família.")
Family.create(:nome => "Delcan", :descr => "Todos os lideres de castelo do planeta Batalha são dessa família. (Mas não necessariamente irmãos.)")
Family.create(:nome => "Erathur", :descr => "Uma das famílias que integram o clã estrela negra. Essa família não é uma das mais importantes.")
Family.create(:nome => "Foldane")
Family.create(:nome => "Gama III Blackfield", :descr => "Família da protagonista do nova era. A parte newkie é da mãe e a parte humana é do pai da Nidja.")
Family.create(:nome => "Kreer", :descr => "Uma das fámilias da tribo dos lobisomens vermelhos.\r\nSildon e Kalryne são irmãos. Kalryne é a mais nova.")
Family.create(:nome => "Lelin", :descr => "Foi essa familia que originalmente criou os felks.")
Family.create(:nome => "Mabert", :descr => "Uma família antiga e pouco conhecida aos dragões comuns. Geralmente seus membros tem atribuições importantes.")
Family.create(:nome => "Mainat", :descr => "Uma das famílias que integram o clã estrela negra.\r\nEssa família não é a mais importante, nem a menos.")
Family.create(:nome => "Morland")
Family.create(:nome => "Netrick", :descr => "Lyia é filha de Tieg e Lua, por ter sido simplesmente um \"presente\" da lua de Hollus (Luna), não tem realmente pais. Pode se dizer até que ela é adotada.")
Family.create(:nome => "Reaven", :descr => "Família do protagonista do newkies")
Family.create(:nome => "Ressek", :descr => "Uma das famílias da tribo dos lobisomens vermelhos.")
Family.create(:nome => "Rettack", :descr => "Família do líder dos lobos vermelhos. Não se sabe se Nith tem algum parentesco com Rayka.")
Family.create(:nome => "Ristair", :descr => "Família do protagonista do ilhas de batalha. Alguns membros certamente vivem em Xuim, uma vila próxima a um penhasco.")
Family.create(:nome => "Roanim")
Family.create(:nome => "Rollinor", :descr => "Família do líder dos lobisomens brancos.")
Family.create(:nome => "Sashvaret", :descr => "Uma das famílias da tribo dos lobisomens vermelhos.")
Family.create(:nome => "Sastar")
Family.create(:nome => "Shoukat")
Family.create(:nome => "Torcom")
Family.create(:nome => "Tuerem")
Family.create(:nome => "Tylladon", :descr => "Família do líder dos lobisomens negros. ")
Family.create(:nome => "Ducan", :descr => "Família techmaga com integrantes pertencentes a cúpula. ")
Family.create(:nome => "Delta IV Beta X", :descr => "Tradicional família Newkie.")
Family.create(:nome => "Sigma II")
Family.create(:nome => "Temark", :descr => "Família com membros na cúpula techmaga.")
Family.create(:nome => "Gama")
Family.create(:nome => "Alfa II")
Family.create(:nome => "Eta V Teta VI", :descr => "Tipica família newkie")
Family.create(:nome => "Cowina")
