ShipSize.create(:nome => "Nave de guerra")
ShipSize.create(:nome => "Cruzador")
ShipSize.create(:nome => "Estrela")
ShipSize.create(:nome => "Explorador")
ShipSize.create(:nome => "Transportador")
ShipSize.create(:nome => "Caça")
