# docker build -t namebook-rails:dev - < Dockerfile.dev
# docker run -v $(pwd):/app -p 3010:3010 -it namebook-rails:dev
FROM ruby:2.7.4-alpine

RUN ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN apk --update add git make gcc mysql-dev nodejs nodejs-dev sqlite-dev patch musl-dev tzdata g++ yarn

RUN adduser -D -u 1000 user
USER user

# gem update bundler Precisa ser executado como user!!!
RUN gem update bundler
WORKDIR /app

EXPOSE 3010
CMD ["sh"]
