name: Docker Image CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build docker and deploy on Techsytes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker login on techsytes
      env:
        TECHSYTES_USER: ${{secrets.TECHSYTES_USER}}
        TECHSYTES_PASSWORD: ${{secrets.TECHSYTES_PASSWORD}}
      run: |
        docker login registry.techsytes.com -u ${TECHSYTES_USER} -p ${TECHSYTES_PASSWORD}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.techsytes.com/namebook-rails:master-${GITHUB_RUN_NUMBER}

    - name: Push the Docker image to DockerHub and Techsytes
      run: |
        docker push registry.techsytes.com/namebook-rails:master-${GITHUB_RUN_NUMBER}

  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
